export default {
    name: '2600',
    '--primary-color': '#f8cc2a',
    '--success-color': 'inherit',
    '--error-color': '#6c3b7b',
    '--body-back-color': '#6c3b7b',
    '--head-text-color': '#f8cc2a',
    '--home-window-back-color': '#1a8ab7',
    '--home-window-text-color': '#f8cc2a',
    '--success-opacity': '.3',
    '--home-countdown-back-color': '#f8cc2a',
    '--home-countdown-text-color': '#6c3b7b',
    '--home-reload-btn-back-color': '#1a8ab7',
    '--home-reload-btn-text-color': '#f8cc2a',
    '--word-count-checked-color': '#1a8ab7',
    '--monkey-caret-color': '#1a8ab7',
} as any;
