export default {
    name: '9009',
    textColor: '#2e2f33',
    '--primary-color': '#6f8c70',
    '--success-color': '#6f8c70',
    '--error-color': '#ec8f88',
    '--body-back-color': '#b6b09a',
    '--head-text-color': '#2e2f33',
    '--home-window-back-color': '#d9d2c8',
    '--home-window-text-color': '#2e2f33',
    '--home-countdown-back-color': '#d9d2c8',
    '--home-countdown-text-color': '#2e2f33',
    '--home-reload-btn-back-color': '#6f8c70',
    '--home-reload-btn-text-color': '#d9d2c8',
    '--word-count-checked-color': '#6f8c70',
    '--monkey-caret-color': '#6f8c70',
} as any;
