export default {
    name: 'default',
    textColor: '#fffffe',
    '@primary-color': '#1890ff',
    '@link-color': '#1890ff',
    '@success-color': '#52c41a',
    '@error-color': '#f5222d',
    '@body-back-color': '#282c34',
    '@text-color-bright': '#fffffe',
    '@home-window-back-color': '#fffffd',
    '@home-window-text-color': '#141414',
    '@home-window-text-acting-back-color': 'rgba(0, 0, 0, 0.26)',
    '@home-el-focus-color': 'rgba(224, 237, 249, 0.21)',
    '@home-countdown-back-color': '#666666',
    '@reload-btn-color': '#fffffe',
} as any;
