export default {
    name: 'nautilus',
    textColor: '#eac004',
    '--primary-color': '#eac004',
    '--body-back-color': '#102c4e',
    '--head-text-color': '#eac004',
    '--home-window-back-color': '#155d94',
    '--home-window-text-color': '#1ae7ea',
    '--home-countdown-back-color': '#155d94',
    '--home-countdown-text-color': '#eac004',
    '--home-reload-btn-back-color': '#eac004',
    '--home-reload-btn-text-color': '#102c4e',
    '--word-count-checked-color': '#1ae7ea',
    '--monkey-caret-color': '#1ae7ea',
} as any;
